In [2]:
from IPython.display import HTML

# Introduction to Scientific Programming in Python

## NumPy Arrays

# Modules and Packages

If someone saves a text file with Python code in it and gives it the ".py" file extension, you can run that file in your own session using the **import** statement. If that file contained functions or new classes, then we get to use them!
  - A **Module** is one Python file.
  - A **Package** is a collection of Python files.
  


## The "Import" Statement, Dot Notation, and Namespaces
To keep from overwriting other functions that may have the same name, Python lets us use the Dot to tell it which packages' function we want to use.  What comes before the dot (or whether a dot is even needed) is referred to as an object's **Namespace**.

In [3]:
import math
import numpy
print(math.sqrt)
print(numpy.sqrt)

<built-in function sqrt>
<ufunc 'sqrt'>


## "From" lets you bring modules and functions into other namespaces. 

In [22]:
from math import sqrt
from numpy import sqrt
sqrt

<ufunc 'sqrt'>

## The "as" operater lets you assign a different variable name in the import statement

In [26]:
import math as m
import numpy as np
my_math_packate = m
my_math_packate

<module 'math' (built-in)>

## Even Packages are objects; They can be renamed the same as anything else once imported.

In [6]:
the_math_package = math
print(the_math_package)

<module 'math' (built-in)>


## Import Submodules with the Dot notation and "as"

In [7]:
import numpy.linalg.norm() as linalg

## Script vs Package
If you have code that you want to run **only** if being called as a script (not being imported as a package): use the following code snippet:

In [8]:
if __name__ == '__main__':
    print('This code runs only in scripts and interactive sessions.')

This code runs only in scripts and interactive sessions.


# The NumPy Package

NumPy is a package for creating, transforming, and calculation with **Arrays** and **Matrices**.  It is the most essential package of the entire Python scientific library. 

The more familiar you are with NumPy, the more effective you will be during data analysis.  So bear with me as I share with you...

## NumPy Array Objects

To construct a **numpy.array**, you should give it an **Iterable**.  It will guess what data type you want, but this can be set with the **dtype** **keyword argument**:

In [27]:
import numpy as np
a_array = np.array([1, 2, 3, 4])
a_array

array([1, 2, 3, 4])

In [28]:
a_float_array = np.array([1, 2, 3, 4], dtype=float)
a_float_array

array([ 1.,  2.,  3.,  4.])

## Array Arithmetic: Now Easy!

By default, all operations are performed **Element-Wise**

In [30]:
data = np.array(range(10), dtype=float)
data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [33]:
data * 2

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [13]:
data * data

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81.])

## Array Arithmetic: Now Fast (on large datasets)!

In [36]:
data = np.array(range(3))
%timeit [el ** 2 for el in data]

The slowest run took 16.31 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.18 µs per loop


In [37]:
%timeit data ** 2

The slowest run took 78.70 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 367 ns per loop


## Arrays Can Be Indexed and Sliced, Just like Tuples and Lists

In [88]:
data = np.array(range(10), dtype=float)
data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [89]:
data[3]

3.0

In [90]:
data[:5]

array([ 0.,  1.,  2.,  3.,  4.])

## Logical Indexing: Using Bool arrays to filter an array

In [50]:
data = np.array(range(4, 20))
# mask = data > 3
dd = data[:5]
dd[1] = 10
data

array([ 4, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Fancy Indexing: Indexing with a list of indices

In [51]:
data[[3, 5, 9]]

array([ 7,  9, 13])

## NumPy comes with Lots of useful math functions!

In [52]:
np.mean(data)

11.8125

In [20]:
HTML('<iFrame src="http://docs.scipy.org/doc/numpy/reference/routines.math.html" width=900 height=300></iFrame>')

## Limitations Of NumPy Arrays
NumPy Arrays are:
  - Fixed-Length (appending them means making a copy)
  - Fixed-Data Type (only one data type in an array)
  

In [56]:
len(data)

16

## Some Array-Creation Shortcut Functions

In [57]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [58]:
np.logspace(3, 10, 5)

array([  1.00000000e+03,   5.62341325e+04,   3.16227766e+06,
         1.77827941e+08,   1.00000000e+10])

In [94]:
np.zeros(4); np.ones(4)
np.zeros_like(data); np.ones_like(data)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Matlab - Python - R Equivalents

For a fairly comprehensive lists of equivalents between languages, see:
http://mathesaurus.sourceforge.net/matlab-python-xref.pdf

In [25]:
HTML('<iFrame src="http://mathesaurus.sourceforge.net/matlab-python-xref.pdf" width=900 height=400></iFrame>')

# Questions and Discussion